name: epitkezes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: checkout repos
        uses: actions/checkout@v3
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: java felporgetese
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: proxy epitese
        run: |
          cd ./mc-reverse-proxy
          chmod +x ./gradlew
          ./gradlew build
          cd ..

      - name: scripting epitese
        run: |
          cd ./reverse-proxy-kotlin-scripting
          cp ../mc-reverse-proxy/standalone/build/libs/standalone-all.jar ./deps
          chmod +x ./gradlew
          ./gradlew build
          cd ..

      - name: scan-ffi epitese
        run: |
          cd ./scan-ffi
          chmod +x ./gradlew
          ./gradlew build
          cd ..

      - name: disztribucio mappa keszitese
        run: |
          mkdir dist
          cd ./dist
          cp ../mc-reverse-proxy/standalone/build/libs/standalone-all.jar .
          mkdir addons
          cp ../reverse-proxy-kotlin-scripting/build/libs/kotlin-scripting-*-all.jar ./addons
          mkdir ./addons/scripts
          cp ../kotlin-scriptek/* ./addons/scripts/
          cp ../scan-ffi/build/libs/jdk17-test-1.0-SNAPSHOT.jar ./scan-ffi.jar
          cd ..

      - name: helper scriptek masolasa
        run: |
          cd ./dist
          cp ../helper-scripts/* .
          cd ..

      - name: data storage
        run: |
          echo "zipname=proxy-ffi-dist-$(TZ='Europe/Budapest' date +%Y-%m-%d-%H-%M).zip" >> $GITHUB_ENV
          echo "date=$(TZ='Europe/Budapest' date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV
          echo "releasename=proxy-ffi-dist | $(TZ='Europe/Budapest' date +'%Y. %m. %d. %H:%M')" >> $GITHUB_ENV

      - name: vegso disztribucio osszeallitasa
        run: |
          zip -r ${{ env.zipname }} ./dist

      - name: release body elkeszitese
        run: |
          chmod +x ./generate-changelog.sh
          ./generate-changelog.sh > body.md
          echo "" >> body.md
          echo "" >> body.md
          echo "(az itt csatolt \`${{ env.zipname }}\` file tartalmazza azt amit keresel)" >> body.md

      - name: release elkeszitese
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.zipname }}
          makeLatest: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          commit: main
          tag: ${{ env.date }}
          name: ${{ env.releasename }}
          bodyFile: "body.md"

      - name: regi releasek kukaba tessek
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
