name: epitkezes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repos
        uses: actions/checkout@v3
        with: 
          submodules: recursive
